### ISSUE TITLE
Markdown header rendering

### ISSUE THREAD

**Issue by jzf2101** [theandygross/TCGA#5]
The markdown headers are not rendering because of missing spaces

See https://github.com/jupyterlab/jupyterlab-demo/pull/36#issuecomment-320345153

**Comment by theandygross** [comment]
Yes this is likely a backwards incomparable Jupyter thing, I'll try and take a pass at cleaning up the formatting this weekend.

**Comment by theandygross** [comment]
Dropped off my radar a while back, fixed the issues that I could see.
